name: CI/CD Pipeline - Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t nikhilnamaji/hello-app:latest ./app

    # ----- Trivy vulnerability scan -----
    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: nikhilnamaji/hello-app:latest
        format: 'table'
        exit-code: 1       # Fail the pipeline if HIGH or CRITICAL vulnerabilities found
        severity: 'CRITICAL,HIGH'

    - name: Push Docker image
      run: docker push nikhilnamaji/hello-app:latest

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Deploy with Helm
      run: |
        helm upgrade --install hello-app ./helm/hello-app \
          --set image.repository=nikhilnamaji/hello-app \
          --set image.tag=latest \
          --namespace default

    - name: Deploy Prometheus & Grafana
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update
        kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
        helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
          --namespace monitoring \
          --set grafana.service.type=LoadBalancer